version: '3'

services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./infrastructure:/workspace
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    working_dir: "/workspace/service"

  app:
    image: rust
    volumes:
      - ./infrastructure/functions:/workspace
    working_dir: "/workspace"
