openapi: "3.0.1"

info:
  title: "Rust Trial"
  version: "v0.0.1"

servers:
  - url: "https://{apiId}.execute-api.ap-northeast-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "v1"
      apiId:
        default: ""

paths:
  /quotes:
    post:
      summary: Famouse Quote
      requestBody:
        description: quote message
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message"
      responses:
        "200":
          description: ok
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${POST_quotes}"
        type: "AWS_PROXY"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        contentHandling: CONVERT_TO_TEXT
        payloadFormatVersion: 2.0
  /quotes/{name}:
    get:
      summary: Famouse Quote
      requestBody:
        description: quote message
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message"
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        "200":
          description: ok
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${GET_quotes_name}"
        type: "AWS_PROXY"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        contentHandling: CONVERT_TO_TEXT
        payloadFormatVersion: 2.0
    put:
      summary: Famouse Quote
      requestBody:
        description: quote message
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message"
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        "200":
          description: ok
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${PUT_quotes_name}"
        type: "AWS_PROXY"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        contentHandling: CONVERT_TO_TEXT
        payloadFormatVersion: 2.0
    delete:
      summary: Famouse Quote
      requestBody:
        description: quote message
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message"
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        "200":
          description: ok
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${DELETE_quotes_name}"
        type: "AWS_PROXY"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        contentHandling: CONVERT_TO_TEXT
        payloadFormatVersion: 2.0

components:
  schemas:
    message:
      type: object
      properties:
        name:
          type: string
